image: atlassian/default-image:2
pipelines:
  default:
    - step:
        script:
          - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
          - docker build -t paweltroc/sms2mail .
          - docker push paweltroc/sms2mail
        services:
          - docker